### ISSUE TITLE
new file types

### ISSUE THREAD

**Issue by paixaop** [lee-dohm/file-type-icons#20]
Hi I've added a few file types to the "Meta configuration file" definitions

[data-name$='.editorconfig']:before,
[data-name$='.esformatter']:before,
[data-name$='.eslintrc']:before,
[data-name$='.eslintignore']:before,
[data-name$='.jsbeautifyrc']:before,
[data-name$='.jscsrc']:before,
[data-name$='.jshintignore']:before,
[data-name$='.jshintrc']:before

if you find it useful please merge them in.
Great job by the way

**Comment by lee-dohm** [comment]
Did you mean for this to be a pull request?

**Comment by lee-dohm** [comment]
Closing because I haven't heard back.
