### ISSUE TITLE
Doubled icons

### ISSUE THREAD

**Issue by thejameskyle** [lee-dohm/file-type-icons#26]
This might be an issue with the latest version of nuclide that is causing this:

<img width="238" alt="screen shot 2016-03-10 at 3 18 35 pm" src="https://cloud.githubusercontent.com/assets/952783/13687945/5fdab794-e6d3-11e5-86c6-9e9392f4a5ff.png">

**Comment by lee-dohm** [comment]
Hmmmm ... strange. I don't use nuclide, so I'm not sure what could be causing this. Does it go away if you collapse and expand the root directory in the tree?

**Comment by thejameskyle** [comment]
> Does it go away if you collapse and expand the root directory in the tree?

Nope, it stays there

**Comment by lee-dohm** [comment]
Ok, I'll see if I can install nuclide and figure it out. No guarantees though.

**Comment by lee-dohm** [comment]
The fix is available in v1.0.0. It requires Atom v1.6.0 though because I didn't test it with any earlier versions.
