### ISSUE TITLE
When the root directory is not a Git repository, it shows up misaligned

### ISSUE THREAD

**Issue by lee-dohm** [lee-dohm/file-type-icons#27]
<img width="215" alt="screen shot 2016-03-21 at 2 18 30 pm" src="https://cloud.githubusercontent.com/assets/1038121/13934523/e7a7570a-ef6f-11e5-8791-764313c31217.png">

**Comment by jensljungblad** [comment]
Mine are misaligned when the root is a git repo as well:

![screen shot 2016-03-22 at 20 54 36](https://cloud.githubusercontent.com/assets/271354/13965879/5f803822-f070-11e5-9fca-b371fc72d8cb.png)

Atom 1.6.0, File type icons 1.0.1

**Comment by lee-dohm** [comment]
Are you using Nuclide?

**Comment by jensljungblad** [comment]
Nope

**Comment by davelandry** [comment]
Same issue here:
<img width="184" alt="screen shot 2016-03-29 at 12 18 06 am" src="https://cloud.githubusercontent.com/assets/1847581/14097851/d8f4cb00-f543-11e5-845b-1a7a4ef77fec.png">

**Comment by swrobel** [comment]
Same issue here, not using Nuclide, on MacOS 10.11.4, tested with Atom 1.6.1 & 1.7.0-beta3 with multiple UI Themes.

![screencast](http://g.recordit.co/zEFNrECbId.gif)

**Comment by Sesna** [comment]
same issue, atom 1.6.1 windows 7
![image](https://cloud.githubusercontent.com/assets/8176600/14199323/085deb2c-f816-11e5-8e62-474b80c2a776.png)

**Comment by davelandry** [comment]
:beers:
