### ISSUE TITLE
One Light theme in Compact mode problem

### ISSUE THREAD

**Issue by AndreaCapigiri** [lee-dohm/file-type-icons#33]
I use One Light theme in Compact mode and i notice that icons and labels are misaligned
<img width="206" alt="screen shot 2016-04-09 at 00 16 41" src="https://cloud.githubusercontent.com/assets/12972252/14398938/66594d8e-fde8-11e5-82aa-8c72ac194eba.png">

**Comment by lee-dohm** [comment]
Please test with the v1.1.0 version of the package to see if that fixes things.

**Comment by AndreaCapigiri** [comment]
Now it works.
Tested with v1.2.0
