### ISSUE TITLE
Tree view icons misaligned in Atom Material UI

### ISSUE THREAD

**Issue by J5lx** [lee-dohm/file-type-icons#37]
When enabling file-type-icons with [Atom Material UI](https://github.com/silvestreh/atom-material-ui) it causes all the icons in the tree view to be misaligned.

Without file-type-icons:
![Atom with file-type-icons disabled: All icons are aligned correctly](https://cloud.githubusercontent.com/assets/2063777/14760908/b4af0276-0950-11e6-9121-f59025b22db5.png)

With file-type-icons:
![Atom with file-type-icons disabled: All icons are misaligned](https://cloud.githubusercontent.com/assets/2063777/14760929/633cfbea-0951-11e6-83f3-a31f0e64779a.png)

Maybe this is related to #33 but since the misalignment occurs with git and non-git directories alike, it’s most likely not related to #27.

**Comment by lee-dohm** [comment]
Please test with the v1.1.0 version of the package to see if that fixes things.

**Comment by J5lx** [comment]
Yep, now it looks much better. Thanks!
