### ISSUE TITLE
Icon is applied to folders

### ISSUE THREAD

**Issue by mfuentesg** [lee-dohm/file-type-icons#41]
This happens when the folder ends with a supported extension.
For example `jquery.rut.js`

![screen shot 2016-05-23 at 11 45 28](https://cloud.githubusercontent.com/assets/8986996/15477844/5f291404-20ed-11e6-8efb-4ed207d36d15.png)

**Comment by panuhorsmalahti** [comment]
👍  can confirm, happens with e.g. `core.js` module.

**Comment by mfuentesg** [comment]
sorry, but now i am working with vim
