### ISSUE TITLE
Elixir icon only applies correctly to folder, not file

### ISSUE THREAD

**Issue by bravely** [lee-dohm/file-type-icons#47]
![screen shot 2016-11-08 at 10 10 48 am](https://cloud.githubusercontent.com/assets/301293/20109053/a666d45e-a59b-11e6-8b90-02ba73f8a901.png)

**Comment by lee-dohm** [comment]
That doesn't appear to be my package.

* I don't use the GitHub icon for `.gitignore`
* I use the Markdown icon for `README.md`
* None of my icons are colored

And my package supports the Elixir icon for both `.ex` and `.exs` files:

<img width="241" alt="screen shot 2016-11-08 at 10 01 28 am" src="https://cloud.githubusercontent.com/assets/1038121/20110745/677eca7c-a59a-11e6-9d5d-65a16ed57cf7.png">

Perhaps you're using @DanBrooker's [file-icons package](https://github.com/DanBrooker/file-icons) instead?

**Comment by bravely** [comment]
I'm quite confident it's yours, as I followed the link here, I didn't do a search.

![screen shot 2016-11-08 at 11 04 30 am](https://cloud.githubusercontent.com/assets/301293/20110842/2a771860-a5a3-11e6-80ed-638e778be123.png)

**Comment by lee-dohm** [comment]
You must have some other package overriding mine then. I just tested this using file-type-icons v1.3.3 and it works as you can see in my screenshot. Perhaps you have a UI theme that is overriding the icons. Have you tried switching back to one of the built-in UI themes?

**Comment by bravely** [comment]
Yeah, I was just testing and that's it. Didn't realize the theme I'm using would cause it- upon disabling, it worked again. Sorry for doubting you, and thanks for the package!

**Comment by lee-dohm** [comment]
You're most welcome :grinning: I'm glad you were able to get it working 👍
